// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import { APPSYNC_API_KEY, IDENTITY_POOL_ID, USER_POOL_ID, WEB_CLIENT_ID } from "./amplify-env"

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_appsync_graphqlEndpoint:
    "https://najx2aa76zb55jeexyyc43nuyy.appsync-api.us-east-2.amazonaws.com/graphql",
  aws_appsync_region: "us-east-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-m72x5g7z7bbofetqly54swhbjy",
  aws_cognito_identity_pool_id: "eu-central-1:8ac45235-934e-4bae-bc7e-c207d3c7e638",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_BV7gxdP7c",
  aws_user_pools_web_client_id: "4jprep7f655r46lh7av2ja4orq",
  oauth: {}
}

export default awsmobile
